"""Add sent column

Revision ID: 2e5416ef0040
Revises: 9bec15259ed5
Create Date: 2022-10-30 13:25:44.160541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e5416ef0040"
down_revision = "9bec15259ed5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tip_reports", sa.Column("sent", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tip_reports", "sent")
    # ### end Alembic commands ###
