"""First migration

Revision ID: 9bec15259ed5
Revises:
Create Date: 2022-09-19 17:45:58.536205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9bec15259ed5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tip_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("latitude", sa.Numeric(), nullable=True),
        sa.Column("longitude", sa.Numeric(), nullable=True),
        sa.Column("number_of_items", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_hazardous", sa.Boolean(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("reported", sa.DateTime(), nullable=True),
        sa.Column("reporter_title", sa.String(), nullable=True),
        sa.Column("reporter_first_name", sa.String(), nullable=True),
        sa.Column("reporter_last_name", sa.String(), nullable=True),
        sa.Column("reporter_email", sa.String(), nullable=True),
        sa.Column("reporter_phone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tip_reports_id"), "tip_reports", ["id"], unique=False)
    op.create_index(
        op.f("ix_tip_reports_latitude"), "tip_reports", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_tip_reports_longitude"), "tip_reports", ["longitude"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tip_reports_longitude"), table_name="tip_reports")
    op.drop_index(op.f("ix_tip_reports_latitude"), table_name="tip_reports")
    op.drop_index(op.f("ix_tip_reports_id"), table_name="tip_reports")
    op.drop_table("tip_reports")
    # ### end Alembic commands ###
